### ISSUE TITLE
Certain values break loading from YAML files.

### ISSUE THREAD

**Issue by oakhan3** [schireson/configly#2]
**Issue:**

I am running into the following error when loading config from a yaml file:

```bash
>>> config = Config.from_yaml("config.yml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/omark/.pyenv/versions/3.9.6/envs/ma-analytics_notebooks-py39/lib/python3.9/site-packages/configly/config.py", line 40, in from_yaml
    return cls.from_loader(YamlLoader(), file, registry=registry)
  File "/Users/omark/.pyenv/versions/3.9.6/envs/ma-analytics_notebooks-py39/lib/python3.9/site-packages/configly/config.py", line 33, in from_loader
    output = post_process(loader=loader, value=result, registry=registry)
  File "/Users/omark/.pyenv/versions/3.9.6/envs/ma-analytics_notebooks-py39/lib/python3.9/site-packages/configly/process.py", line 11, in post_process
    result[key] = post_process(loader, item, registry=registry)
  File "/Users/omark/.pyenv/versions/3.9.6/envs/ma-analytics_notebooks-py39/lib/python3.9/site-packages/configly/process.py", line 47, in post_process
    return loader.load_value(result)
  File "/Users/omark/.pyenv/versions/3.9.6/envs/ma-analytics_notebooks-py39/lib/python3.9/site-packages/configly/loaders.py", line 25, in load_value
    return self.decoder.load(value)
  File "/Users/omark/.pyenv/versions/3.9.6/envs/ma-analytics_notebooks-py39/lib/python3.9/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/Users/omark/.pyenv/versions/3.9.6/envs/ma-analytics_notebooks-py39/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 120, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 703, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: while scanning a block scalar
  in "<unicode string>", line 1, column 1
did not find expected comment or line break
  in "<unicode string>", line 1, column 2

while scanning a block scalar
  in "<unicode string>", line 1, column 1
did not find expected comment or line break
  in "<unicode string>", line 1, column 2

```

**To reproduce:**

1. Export a value like the following into the environment:

`BAD_VAL=">eP2CoFHt*Ppram37DDmF_D=Wuueu-w6H]~HH%bTCq7Lk%q"`

2. Create a config.yml like the following:

```yaml
bad_val: <% ENV[BAD_VAL, null] %>
```

3. Load the config:

```python
from configly import Config
config = Config.from_yaml('config.yml')
```

**Expected Behavior:**

Configly treats the "bad_value" like any other quoted string value and does not throw an error.

**Comment by oakhan3** [comment]
The bad character in this case seems to be the `>` at the beginning of the value.

**Comment by oakhan3** [comment]
It's likely because of YAML multi-line/block syntax - 
```yaml
Key: >
  This is a multi
  line
  string
```

**Comment by oakhan3** [comment]
This is only one example^ I think all string values need to be quoted when they are interpolated into a given YAML file to avoid them being misinterpreted as part of the syntax. Especially true for values that begin with none-alphanumeric characters. I will work on a fix for this and submit a PR.
